name: CI Pipeline

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build Project
              run: echo "ravi building project..."

    test: 
        runs-on: ubuntu-latest
        steps:
            - name: Run tests
              run: echo "ravi running tets..."

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy project
              run: echo "ravi deploying project"