name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Save node_modules as artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: node_modules

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules
          path: ./node_modules

      - name: Run tests
        run: echo "testing the project"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules
          path: ./node_modules

      - name: Deploy project
        run: |
          node index.js &
          sleep 5
          echo "Server started successfully!"