name: CI Pipeline

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build Project
              run: echo "Building the project..."
              
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Run tests
              run: echo "testing the project"

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy project
              run: echo "deploying the project"
